### ISSUE TITLE
Streamline the patient intake process

### ISSUE THREAD

**Issue by JonasDju** [JonasDju/HospiTool#9]
### Motivation
The current patient intake process is not straight forward and allows for inconsistent states (like selecting an existing patient AND selecting emergency intake data at the same time). The process should therefore be made more 'linear' to reduce the risk of accidentally submitting wrong information and improving the intuitiveness.

### Proposed Solution
When clicking the 'Patient Intake' tab in the sidebar, the user is presented with three options: 'Select existing patient', 'Create new patient' and 'Perform emergency intake'. The last option should only be visible to users working in the emergency department. Besides these three options, the rest of the UI is empty. Once one of the buttons is pressed, the user is taken to a site where the required patient information is entered (depending on which method has been selected beforehand). After confirming the patient data, the user is taken to the last page, where the required intake information can be entered (Diagnosis code, Note, Admission / discharge date, Ward, Accompanied, …).

**Comment by matthisfranzgrote** [comment]
### Additional issue: Discharge date
- rather than selecting the discharge date by calendar, have user enter a stay duration in days
- calendar view still available as an alternative/visually checking where the discharge is estimated to take place
- add capability of selecting allowed discharge days (e.g. mo/tue only) per ward and automatically postponing discharge to the next available day
- for all of the above, give appropriate user feedback whenever the date changes without an explicit user action
- optional: incorporate fetching estimated stay duration based on ICD-10 diagnosis

**Comment by JonasDju** [comment]
The bugfixes for #20 and #23 have been merged into `dev` and are therefore available to be integrated into your branch.
